### PR TITLE
Changed .h files

### PR DESCRIPTION
**Pull request by TomasRoj**
Hey,

I looked at your code and deleted every .h file and left only one for all RTCs. Its in the root folder. Hope it will work!

-Tomas

### CODE REVIEW

**Comment by cvmanjoo** [comment]
Hey,

I guess this works, 
can u check there is conflict with **PCF8563.h**"

And name header file as **RTC.h** If you want merge all the .h files.

-Manjunath

**Comment by TomasRoj** [comment]
I dont understand what you did. You removed the rtc-clocks.h and reverted all the files what?

**Comment by cvmanjoo** [comment]
Oh! Yes i believe.
There were changes in my PCF8563.h file.

Apologies, Can you push it again?

**Comment by TomasRoj** [comment]
Hey,

I pushed again but idk why there is that conflict.

**Comment by cvmanjoo** [comment]
May be because I added some new functions to PCF8563.

It doesn't work. Because how do we select RTC? 
You have any better Idea?

**Comment by TomasRoj** [comment]
What features?

**Comment by TomasRoj** [comment]
click resolve conflicts

**Comment by TomasRoj** [comment]
or give me write acces

**Comment by TomasRoj** [comment]
give me write access bro

**Comment by cvmanjoo** [comment]
Done added you as collaborator

**Comment by TomasRoj** [comment]
Ok try to give back that file

**Comment by TomasRoj** [comment]
It looks i still dont have write acces. It says only those with write acces to this repository can merge pull requests

**Comment by TomasRoj** [comment]
Ok is it all ok?

**Comment by cvmanjoo** [comment]
Nope, I couldn't merge your changes.

**Comment by TomasRoj** [comment]
Try it now.

**Comment by TomasRoj** [comment]
ok thanks! I have few more changes. Tommorow i will push it.

**Comment by cvmanjoo** [comment]
Sure, I will move RTC.h to src folder. Its belong there.

**Comment by TomasRoj** [comment]
btw. Why u start communication in every method again? User can just use start method once and then other methonds.

**Comment by cvmanjoo** [comment]
Ok. Update that push. I will test it.

**Comment by TomasRoj** [comment]
its in every method. I will do that tommorow. I hav elibrary too. Can you contribute? Its for beginners

**Comment by cvmanjoo** [comment]
Ok  I shall Check that

**Comment by TomasRoj** [comment]
Thanks!

**Comment by TomasRoj** [comment]
You can just write some simple methods (examples) for example display control etc.

**Comment by cvmanjoo** [comment]
Sure i will check that. When i get time.

**Comment by TomasRoj** [comment]
Ok, so please fork that my library and tommorow i will push new changes to yours. bye for now.

**Pull request merged**
